### ISSUE TITLE
Write access

### ISSUE THREAD

**Issue by mperry** [Frege/frege-interpreter#13]
@mmhelloworld Can I get write access directly to this repo?  I want to get Travis CI and uploading to Sonatype working and having to create PR to test is not efficient.  Access can be revoked once this is working.

**Comment by mperry** [comment]
If this is ok, it would make sense to grant access to frege-repl and native-gen too.

**Comment by mmhelloworld** [comment]
I have created a new team called continuous-integration and added you as a member. The members of the team have write access to frege-interpreter, frege-repl and frege-native-gen repos. Please let me know if you still have any issues. Thanks for doing all this work!

**Comment by mperry** [comment]
Thanks for that.  Trying to make getting started in Frege easier for the people coming after me.
