### ISSUE TITLE
Frege interpreter should have an official release

### ISSUE THREAD

**Issue by mperry** [Frege/frege-interpreter#15]
@mmhelloworld  The interpreter has never had an official release, only snapshot releases.  The current version is marked 1.0.3-SNAPSHOT.  Is this appropriate still?  Would you like me to release 1.0.3 as is?  Perhaps the next version should be marked 1.1-SNAPSHOT.  For the continuous integration builds see https://oss.sonatype.org/content/groups/public/org/frege-lang/frege-interpreter-core/.

**Comment by mperry** [comment]
@mmhelloworld ping.

**Comment by mmhelloworld** [comment]
That sounds good. We can release 1.0.3 with the current code and plan for the next version as 1.0-SNAPSHOT. Thanks for doing this!

**Comment by mperry** [comment]
I think you mean the next version is 1.1-SNAPSHOT.

**Comment by mperry** [comment]
This component now has 1.0.3 and 1.0.4 releases.
