### ISSUE TITLE
Does not compile with 3.22.524

### ISSUE THREAD

**Issue by mperry** [Frege/frege-interpreter#18]
Build message on my machine is below, this looks the same as the Travis CI build (https://travis-ci.org/Frege/frege-interpreter/builds/72127990):

D:\repositories\frege-interpreter>gradlew clean build
:frege-interpreter-core:clean
:frege-interpreter-distribution:clean
:frege-interpreter-java-support:clean
:frege-script-engine:clean
:frege-interpreter-java-support:compileFrege
runtime 0.493 wallclock seconds.
:frege-interpreter-java-support:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: D:\repositories\frege-interpreter\frege-interpreter-java-support\src\main\java\frege\interpret
er\javasupport\JavaUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:frege-interpreter-java-support:compileGroovy UP-TO-DATE
:frege-interpreter-java-support:processResources UP-TO-DATE
:frege-interpreter-java-support:classes
:frege-interpreter-java-support:jar
:frege-interpreter-core:compileJava UP-TO-DATE
:frege-interpreter-core:compileFrege
parsing D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\Fr
egeInterpreter.fr
Compiler.Classes: no rebuild needed because module exists on class path and no source available.
Compiler.Typecheck: no rebuild needed because module exists on class path and no source available.
Compiler.enums.Flags: no rebuild needed because module exists on class path and no source available.

frege.Prelude: no rebuild needed because module exists on class path and no source available.
Compiler.GenMeta: no rebuild needed because module exists on class path and no source available.
Compiler.GenJava7: no rebuild needed because module exists on class path and no source available.
Compiler.common.CompilerOptions: no rebuild needed because module exists on class path and no source
 available.
Compiler.grammar.Lexer: no rebuild needed because module exists on class path and no source availabl
e.
Compiler.types.External: no rebuild needed because module exists on class path and no source availab
le.
Compiler.enums.TokenID: no rebuild needed because module exists on class path and no source availabl
e.
Compiler.passes.Enter: no rebuild needed because module exists on class path and no source available
.
Compiler.classes.Nice: no rebuild needed because module exists on class path and no source available
.
Compiler.Transform: no rebuild needed because module exists on class path and no source available.
Compiler.passes.Instances: no rebuild needed because module exists on class path and no source avail
able.
Compiler.common.Desugar: no rebuild needed because module exists on class path and no source availab
le.
Compiler.passes.Transdef: no rebuild needed because module exists on class path and no source availa
ble.
Compiler.passes.Imp: no rebuild needed because module exists on class path and no source available.
Compiler.passes.TypeAlias: no rebuild needed because module exists on class path and no source avail
able.
Compiler.grammar.Frege: no rebuild needed because module exists on class path and no source availabl
e.
Compiler.types.Packs: no rebuild needed because module exists on class path and no source available.

Control.monad.State: no rebuild needed because module exists on class path and no source available.
Compiler.passes.Fix: no rebuild needed because module exists on class path and no source available.
Compiler.types.Positions: no rebuild needed because module exists on class path and no source availa
ble.
Compiler.types.SNames: no rebuild needed because module exists on class path and no source available
.
Compiler.types.SourceDefinitions: no rebuild needed because module exists on class path and no sourc
e available.
Compiler.types.Tokens: no rebuild needed because module exists on class path and no source available
.
Compiler.common.Resolve: no rebuild needed because module exists on class path and no source availab
le.
Compiler.types.NSNames: no rebuild needed because module exists on class path and no source availabl
e.
Compiler.types.Global: no rebuild needed because module exists on class path and no source available
.
Compiler.common.Errors: no rebuild needed because module exists on class path and no source availabl
e.
Compiler.passes.Fields: no rebuild needed because module exists on class path and no source availabl
e.
Data.TreeMap: no rebuild needed because module exists on class path and no source available.
Java.util.Regex: no rebuild needed because module exists on class path and no source available.
Control.arrow.Kleisli: no rebuild needed because module exists on class path and no source available
.
Control.monad.Reader: no rebuild needed because module exists on class path and no source available.

Data.List: no rebuild needed because module exists on class path and no source available.
Compiler.types.QNames: no rebuild needed because module exists on class path and no source available
.
Prelude.PreludeIO: no rebuild needed because module exists on class path and no source available.
Prelude.PreludeList: no rebuild needed because module exists on class path and no source available.
Lib.PP: no rebuild needed because module exists on class path and no source available.
Prelude.PreludeText: no rebuild needed because module exists on class path and no source available.
Prelude.PreludeMonad: no rebuild needed because module exists on class path and no source available.

Prelude.PreludeBase: no rebuild needed because module exists on class path and no source available.
Compiler.types.Symbols: no rebuild needed because module exists on class path and no source availabl
e.
Ide.Utilities: no rebuild needed because module exists on class path and no source available.
Prelude.PreludeArrays: no rebuild needed because module exists on class path and no source available
.
Compiler.types.Types: no rebuild needed because module exists on class path and no source available.

Interpreter.FregeInterpreter: compiling because class file doesn't exist
W D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:640: hiding previously (line 6)
    imported alias for instance `Lang.PrimitiveArrayElement_Byte` through instance `PrimitiveArrayEl
ement_Byte`
W D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:178: ST.performUnsafe: You are
    breaking the rules. Expect an arbitrary result and program crashes.
W D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:196: ST.performUnsafe: You are
    breaking the rules. Expect an arbitrary result and program crashes.
W D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:206: ST.performUnsafe: You are
    breaking the rules. Expect an arbitrary result and program crashes.
W D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:224: ST.performUnsafe: You are
    breaking the rules. Expect an arbitrary result and program crashes.
W D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:326: ST.performUnsafe: You are
    breaking the rules. Expect an arbitrary result and program crashes.
W D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:351: ST.performUnsafe: You are
    breaking the rules. Expect an arbitrary result and program crashes.
W D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:356: ST.performUnsafe: You are
    breaking the rules. Expect an arbitrary result and program crashes.
W D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:422: ST.performUnsafe: You are
    breaking the rules. Expect an arbitrary result and program crashes.
W D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:423: ST.performUnsafe: You are
    breaking the rules. Expect an arbitrary result and program crashes.
W D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:640: data type `Lang.Byte` is
    already an instance of class `PrimitiveArrayElement` (Lang.PrimitiveArrayElement_Byte introduced
 on line 1)
W D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:640: data type `Lang.Byte` is
    already an instance of class `ArrayElem` (Lang.PrimitiveArrayElement_Byte introduced on line 1)
W D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:640: data type `Lang.Byte` is
    already an instance of class `JavaType` (Lang.PrimitiveArrayElement_Byte introduced on line 1)
E D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:660: Non pure native type
    InterpreterClassLoader must be MutableIO InterpreterClassLoader in IO actions.
E D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:663: Non pure native type
    InterpreterClassLoader must be MutableIO InterpreterClassLoader in IO actions.
E D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:657: Non pure native type
    InterpreterClassLoader must be Mutable s InterpreterClassLoader in ST actions.
H D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:205: immutable frege.interpreter.javasupport.InterpreterClassLoader cannot be used as su
btype of mutable only java.net.URLClassLoader
E D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:205: type error in  expression
    classLoader state
    type is   InterpreterClassLoader
    used as   Net.URLClassLoader
H D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:327: immutable frege.interpreter.javasupport.InterpreterClassLoader cannot be used as su
btype of mutable only java.net.URLClassLoader
E D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInt
erpreter.fr:327: type error in  expression
    default
    type is   InterpreterClassLoader
    used as   Net.URLClassLoader
Interpreter.FregeInterpreter: build failed because of compilation errors.
Build failed.
runtime 9.453 wallclock seconds.
:frege-interpreter-core:compileFrege FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':frege-interpreter-core:compileFrege'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_40\bin\java.exe'' finished with non-zero exit val
ue 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more l
og output.

BUILD FAILED

Total time: 45.373 secs

D:\repositories\frege-interpreter>

**Comment by mperry** [comment]
Any chance of looking into this @mmhelloworld?

**Comment by mmhelloworld** [comment]
Yes, I am working on it currently. `frege-interpreter` is not compatible with the new version and so are `frege-repl` and `try-frege`. It is almost done. All the 3 projects now work with the new version but I am still working on a new UI for the online REPL. I will push these changes either today or tomorrow EST.

**Comment by mperry** [comment]
I think this is the last issue before moving the gradle plugin to using 3.22.524, so your progress sounds really promising.

**Comment by mperry** [comment]
Looks like this is resolved by #19.

**Comment by mmhelloworld** [comment]
Yes, this can be closed. I just now got a successful build on Travis and merged my changes to master. Thanks for reporting this issue and following up!
