### ISSUE TITLE
code hides previously imported alias

### ISSUE THREAD

**Issue by mperry** [Frege/frege-interpreter#26]
I suspect this should not be occurring when building using Gradle:

Interpreter.FregeInterpreter: compiling because class file doesn't exist
W D:\repositories\frege-interpreter\frege-interpreter-core\src\main\frege\frege\interpreter\FregeInterpreter.fr:52: hiding previously (line 13)
    imported alias for function `Global.liftIO` through alias for class member value `MonadIO.MonadIO.liftIO`

**Comment by valeryprayd** [comment]
Agreed. Right now build fails. With --debug option I am getting this:

13:39:03.860 [ERROR] [system.err] W /home/vagrant/frege-repl/frege-repl-core/src/main/frege/frege/repl/FregeRepl.fr:17: hiding previously (line 9) imported alias for function
13:39:03.861 [ERROR] [system.err]     `Global.liftIO` through alias for class member value `MonadIO.MonadIO.liftIO`
13:39:03.866 [ERROR] [system.err] W /home/vagrant/frege-repl/frege-repl-core/src/main/frege/frege/repl/FregeRepl.fr:19: hiding previously (line 12) imported alias for data type
13:39:03.866 [ERROR] [system.err]     `Swing.JTextComponent` through alias for data type `Gui.JTextComponent`
13:39:03.866 [ERROR] [system.err] W /home/vagrant/frege-repl/frege-repl-core/src/main/frege/frege/repl/FregeRepl.fr:19: hiding previously (line 12) imported alias for data type
13:39:03.866 [ERROR] [system.err]     `Swing.JPanel` through alias for data type `Gui.JPanel`
13:39:03.866 [ERROR] [system.err] W /home/vagrant/frege-repl/frege-repl-core/src/main/frege/frege/repl/FregeRepl.fr:19: hiding previously (line 12) imported alias for data type
13:39:03.870 [ERROR] [system.err]     `Swing.JComponent` through alias for data type `Gui.JComponent`
13:39:06.728 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED

**Comment by Ingo60** [comment]
Looks to me like gradle interprets the warnings as errors?

**Comment by valeryprayd** [comment]
Turned out this was caused by insufficient memory on my vagrant box, error just coincided with warnings, so, false alarm.
