### ISSUE TITLE
Remove the binary file lib/frege*.jar from the repo

### ISSUE THREAD

**Issue by mperry** [Frege/frege-interpreter#29]
I tried to remove the jar file from the repo.   The following command shows the large files:

` git verify-pack -v .git/objects/pack/*.idx | sort -k 3 -n | tail -5`

I am not sure if it is removed or not.  Can a clever person go and look and remove the jar file from the git history if not already done?

**Comment by mperry** [comment]
I used the BFG repo cleaner (https://rtyley.github.io/bfg-repo-cleaner/) and think I have solved the problem. I ran:

```
git clone --mirror git://github.com/Frege/frege-interpreter.git
java -jar bfg-1.12.6.jar  --strip-blobs-bigger-than 2M frege-interpreter.git/
cd frege-interpreter.git
 git reflog expire --expire=now --all && git gc --prune=now --aggressive
git push  https://github.com/Frege/frege-interpreter.git --force
```

**Comment by mperry** [comment]
We need someone to double check what I have done.  Once this is confirmed as ok, we need everyone to delete local repos and clone again from Github.  We don't want the large binary files to be exploding the size of the repo.

**Comment by mperry** [comment]
@mmhelloworld and @Dierk, can you check what I have done?

**Comment by mmhelloworld** [comment]
We can delete the local jar. It was just a temporary solution until the latest frege was available on maven central. I already removed it from the build but forgot to remove the local jar. Thanks for looking into this!
