### ISSUE TITLE
Add OSGi support

### ISSUE THREAD

**Issue by renatoathaydes** [Frege/frege-interpreter#31]
Hi,

I have noticed that even though frege-core is OSGi-ready, the frege-interpreter isn't.

Do you have plans to add OSGi support?

I've tried to wrap the interpreter into a bundle but unfortunately it seems the way Frege loads classes doesn't work inside OSGi.

Errors I get:

```
frege.runtime.Undefined: [E <console>.fr:1: Could not import module frege.Prelude
    (java.lang.ClassNotFoundException: frege.Prelude), E <console>.fr:1: Could not import module frege.prelude.PreludeBase
    (java.lang.ClassNotFoundException: frege.prelude.PreludeBase), E <console>.fr:1: Could not import module frege.prelude.PreludeList
    (java.lang.ClassNotFoundException: frege.prelude.PreludeList), E <console>.fr:1: Could not import module frege.prelude.PreludeText
    (java.lang.ClassNotFoundException: frege.prelude.PreludeText), E <console>.fr:1: Could not import module frege.prelude.PreludeMonad
    (java.lang.ClassNotFoundException: frege.prelude.PreludeMonad), E <console>.fr:1: Could not import module frege.prelude.PreludeIO
    (java.lang.ClassNotFoundException: frege.prelude.PreludeIO), E <console>.fr:1: Could not import module frege.prelude.PreludeArrays
    (java.lang.ClassNotFoundException: frege.prelude.PreludeArrays), E <console>.fr:1: Could not import module frege.java.util.Regex
    (java.lang.ClassNotFoundException: frege.java.util.Regex)]
```

If you can give any ideas on how this may work or you will add support for OSGi soon, I would appreciate.

**Comment by Ingo60** [comment]
FYI, the compiler uses `Class.forName` and `Class.getAnnotation` to load information from class files.

I'm really not sure why  OSGi would not allow this, and I hope @talios will comment on it.

BTW, the eclipse-plugin is also a bundle (or is it?), and the same (compiler) code  is working just fine there.

**Comment by renatoathaydes** [comment]
If it were possible to set the ClassLoader to use to load classes, I believe this problem could be avoided.

**Comment by renatoathaydes** [comment]
See http://njbartlett.name/2010/08/30/osgi-readiness-loading-classes.html.

**Comment by Ingo60** [comment]
This is not possible, nor should it be needed (I think).
The compiler creates a class loader for the purpose of module imports:

    ClassLoader.current >>= URLClassLoader.new urlarr

which should be more or less equivalent to Java

     new URLClassLoader(urlarr, frege.runtime.Meta.FregePackage.class,getClassLoader())

where `urlarr` is an array of URLs built from 

  1. the current class path (unless `-nocp` option is given)
  2. the value of the option `-fp` (i.e frege path)

The rather complicated way to crete the class loader (and to create a separate class loader at all) results from difficulties in eclipse to get away with the default class loader, as far as I remember. In any case, it is so that the eclipse plugin (which uses the same code as the batch compiler and the REPL) is able to load  **different** library modules than the one it is running itself. (Isn't that what OSGi is all abut?)

So I guess all you need is a way to tell the REPL where the standard library it is suposed to use is located?

**Comment by Ingo60** [comment]
I actuall erred rgd. `forName`, actually we use `ClassLoader.loadClass`

**Comment by renatoathaydes** [comment]
In OSGi, each bundle (roughly a jar) has its own classloader, and can see only the classes it imports from other bundles. There's no single classpath, as in regular Java applications.

Is it possible to pass the `-fp` option programmatically, as obviously I am using frege-interpreter as just a dependency of my application, not running it from the command line.

**Comment by Ingo60** [comment]
I'm not sure if system property `java.class.path` can be altered. 
If it is, this would be morally equivalent to invoke the compiler with a certain class path, and would result in a class loader that uses that path. Just make sure to use the correct `path.separator`

**Comment by renatoathaydes** [comment]
The interpreter is fundamentally at odds with how OSGi works. I added support for "system libs" in my Gradle plugin [osgi-run](https://github.com/renatoathaydes/osgi-run) so that I can run code like this, that wants to load its own classes, from OSGi.

Here's how it works (if anyone in the future is interested in this: https://github.com/renatoathaydes/osgi-run/pull/44/commits/9563d80014f1ac2e74e3728d7141f01db602cd24)

**Comment by talios** [comment]
I was meaning to respond to this the other day, the latest Frege.jar that I'm publishing to Maven Central now no-longer has OSGi exports added ( I was originally repacking the entire jar, but now that I'm publishing both the jdk7 and jdk8 flavours that was getting a bit awkward. ).

Ideally we should get the @Ingo60's release process ( the MakeFile? ) to add he `MANIFEST.MF` entries when creating the jar file.

**Comment by renatoathaydes** [comment]
@talios Just adding the manifest entries is not enough to get the Frege interpreter to run in OSGi. Specifically, the way you load classes at runtime (which I don't know if only the interpreter does, or core also does) cannot work in OSGi unless you let users provide a classloader.
